name: CI
on:
  push:
    branches: [main]
jobs:
  onestage:
    runs-on: ubuntu-latest
    steps:
      - name: Copy my repository
        uses: actions/checkout@v4
        #Build my containers
      - name: Build containers
        run: docker compose build
       # Start containers
      - name: start containers
        run: docker compose up -d
      # check work containers
      - name: check the containers
        run: docker compose ps -a

      - name: wait for backend
        run: |
          for i in $(seq 1 30); do
          if curl -f http://localhost:4000/health; then
          echo "backend ready"
            exit 0
          fi
          echo "waiting... attempt $i"
          sleep 2
          done
          echo "backend did not start in time"
          exit 1

      - name: test chat
        run: docker compose exec -T back node test_chat.js | tee test-report.txt # выполни команду внутри контейнера,back - имя сервиса, node - программа которую запустим, test_chat.js - аргумент программы
      - uses: actions/upload-artifact@v4 #Сохраняем ответ
        with:
          name: test-results
          path: test-report.txt

      #Логинимся в Docker Hub для переноса наших проектов туда
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{  secrets.DOCKER_PASSWORD }}

      - name: build and push backend
        run: |
          docker tag chat-messenger-back glimpl/chat-messenger-back:latest
          docker push glimpl/chat-messenger-back:latest
      - name: build and push frontend
        run: |
          docker tag chat-messenger-front glimpl/chat-messenger-front:latest
          docker push glimpl/chat-messenger-front:latest

      #deploy
  deploy:
    runs-on: self-hosted
      needs: [test]
      steps:
        - name: Run my repository
          uses: actions/checkout@v4

        #Login docker hub что бы забрать
        - name: login to docker hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{  secrets.DOCKER_PASSWORD }}
        #pull
        - name: pull images
          run: docker compose pull
        - name: start
          run: docker compose up -d